on:
  schedule:
    - cron: "0 0 * * 1-5" # Run every day of the week (Monday to Friday) at midnight UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and deploy your website here
